
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    expose:
      - "5252"

  backend2:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    expose:
      - "5252"    

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    expose:
      - "9000"
    depends_on:
      - backend

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - backend2
